language: node_js
node_js:
  - 7

branches:
  except:
  - gh-pages

cache:
  directories:
    - node_modules

before_script:
  - cd evento

script:
  - npm install
  - npm run travis-test
  - npm run build

after_success:
  - git config --global user.email "${GIT_EMAIL}"
  - git config --global user.name "${GIT_COMMIT_DISPLAYNAME}"
  - git remote set-url origin https://${GH_USER}:${GH_TOKEN}@github.com/${GH_USER}/${GH_REPO}.git
  - npm run deploy
