language: node_js
node_js:
  - 7

branches:
  except:
  - gh-pages

cache:
  directories:
    - node_modules

before_install:
  - cd evento

script:
  - npm install
  - npm test a
  - npm run build

after_success:
  - git config --global user.email "jaakko.lipsanen@outlook.com"
  - git config --global user.name "Travis CI"
  - git remote set-url origin https://JaakkoLipsanen:${GIT_TOKEN}@github.com/JaakkoLipsanen/evento-web.git
  - npm run deploy
