language: node_js
node_js:
  - 7

branches:
  except:
  - gh-pages

cache:
  directories:
    - node_modules

before_script:
  - cd evento

script:
  - npm install
  - npm run travis-test
  - npm run build

after_success:
  - cd ..
  - chmod +x deploy.sh # make deploy script executable
  - ./deploy.sh
