language: node_js
node_js:
  - 7
cache:
  directories:
    - node_modules
script:
  - cd evento
  - npm install
  - npm test a
  - npm run build
after_success:
  - cd evento
  - git config --global user.email "jaakko.lipsanen@outlook.com"
  - git config --global user.name "Jaakko Lipsanen (built by Travis)"
  - npm run deploy
