language: node_js
node_js:
  - 7

branches:
  except:
  - gh-pages

cache:
  directories:
    - node_modules

script:
  - npm install
  - npm test a
  - npm run build

after_success:
  - npm run deploy

before_install:
  - cd evento
  - openssl aes-256-cbc -K $encrypted_f41f5a831225_key -iv $encrypted_f41f5a831225_iv
    -in id_rsa.enc -out ~\/.ssh/id_rsa -d

env:
  global:
    - DEPLOY_BRANCH="master"
    - SOURCE_DIR="build"
    - TARGET_BRANCH="gh-pages"
    - SSH_KEY="id_rsa"
    - GIT_NAME="Travis"
    - GIT_EMAIL="jaakko.lipsanen@outlook.com"
